services:
  postgres:
    image: postgres:16-alpine
    container_name: aurora-postgres
    environment:
      POSTGRES_DB: aurora_blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: aurora-api
    depends_on:
      - postgres
    environment:
      PORT: 3000
      APP_URL: http://localhost:3000
      WEB_URL: http://localhost:8080
      ADMIN_URL: http://localhost:8081
      JWT_SECRET: aurora_super_secret_jwt_key
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/aurora_blog?schema=public
      UPLOAD_DIR: uploads
    ports:
      - "3000:3000"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: aurora-web
    depends_on:
      - api
    ports:
      - "8080:80"

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    container_name: aurora-admin
    depends_on:
      - api
    ports:
      - "8081:80"

volumes:
  postgres_data:
